// <auto-generated />
using System;
using IMS.Plugins.EFCoreSqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMS.Plugins.EFCoreSqlServer.Migrations
{
    [DbContext(typeof(IMSContext))]
    [Migration("20251128190753_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMS.CoreBusiness.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aluminum Frame",
                            Price = 250.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carbon Frame",
                            Price = 600.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wheel Set 30\"",
                            Price = 150.00m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wheel 20\"",
                            Price = 40.00m,
                            Quantity = 120
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wheel 26\"",
                            Price = 75.00m,
                            Quantity = 150
                        },
                        new
                        {
                            Id = 6,
                            Name = "Disc Brake Set",
                            Price = 120.00m,
                            Quantity = 80
                        },
                        new
                        {
                            Id = 7,
                            Name = "Electric Motor Kit",
                            Price = 800.00m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gear System 21-Speed",
                            Price = 180.00m,
                            Quantity = 70
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gear System 7-Speed",
                            Price = 80.00m,
                            Quantity = 90
                        },
                        new
                        {
                            Id = 10,
                            Name = "Suspension Fork",
                            Price = 200.00m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 11,
                            Name = "Battery Pack",
                            Price = 400.00m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pedals",
                            Price = 35.00m,
                            Quantity = 200
                        });
                });

            modelBuilder.Entity("IMS.CoreBusiness.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("DoneBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mountain Trail Pro",
                            Price = 1299.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "City Commuter Elite",
                            Price = 899.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Road Racer X500",
                            Price = 1899.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Electric Cruiser Plus",
                            Price = 2499.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kids Explorer 20",
                            Price = 549.99m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("IMS.CoreBusiness.ProductInventory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "InventoryId");

                    b.HasIndex("InventoryId");

                    b.ToTable("ProductInventories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            InventoryId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 1,
                            InventoryId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 1,
                            InventoryId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 1,
                            InventoryId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 1,
                            InventoryId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 1,
                            InventoryId = 12,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 2,
                            InventoryId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 2,
                            InventoryId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 2,
                            InventoryId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 2,
                            InventoryId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 2,
                            InventoryId = 12,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 3,
                            InventoryId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 3,
                            InventoryId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 3,
                            InventoryId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 3,
                            InventoryId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 3,
                            InventoryId = 12,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryId = 12,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 5,
                            InventoryId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 5,
                            InventoryId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 5,
                            InventoryId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 5,
                            InventoryId = 12,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("IMS.CoreBusiness.ProductTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("DoneBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("int");

                    b.Property<string>("SONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTransactions");
                });

            modelBuilder.Entity("IMS.CoreBusiness.InventoryTransaction", b =>
                {
                    b.HasOne("IMS.CoreBusiness.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("IMS.CoreBusiness.ProductInventory", b =>
                {
                    b.HasOne("IMS.CoreBusiness.Inventory", "Inventory")
                        .WithMany("Products")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.CoreBusiness.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IMS.CoreBusiness.ProductTransaction", b =>
                {
                    b.HasOne("IMS.CoreBusiness.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Inventory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IMS.CoreBusiness.Product", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
